### PR TITLE
Add new feature Date Range

### PR DESCRIPTION
**Pull request by Husseinhj**
Hi dude
I try to test the last version and find out some bug in Persian calendar. I've fix this stuff
I was thinking how can i add new feature? so i decided to implement Date Range to select a range of date, you need to use Long Press.

English range selection
Persian range selection

Thank you
Hussein Habibi Juybari

### CODE REVIEW

**Comment by maximbilan** [comment]
Thanks.

**Comment by Husseinhj** [comment]
Your welcome @maximbilan ;-)

**Comment by Husseinhj** [comment]
Sorry, did you merge with the master branch? 
I want to use pod in my project

**Comment by maximbilan** [comment]
@Husseinhj Done. Please use.

**Comment by Husseinhj** [comment]
@maximbilan Thanks

**Pull request merged**
