### PR TITLE
Add locale and CalendarIdentifier

### PR DESCRIPTION
**Pull request by Husseinhj**
Hi dude
I've added locale and CalendarIdentifier for suppor calendar All type of locale for example Persian and etc ...
And add some cool stuff you may enjoy

persian home

persian popup

thanks in advance
Hussein Habibi Juybari

### CODE REVIEW

**Comment by maximbilan** [comment]
Thanks a lot.
Could you please add some documentation about these features in README.md if you have time?
Thanks in advance.

**Comment by Husseinhj** [comment]
Yes sure. I'll add documents in README.md file

**Comment by maximbilan** [comment]
@Husseinhj thanks, man, I really appreciate it.

**Comment by Husseinhj** [comment]
@maximbilan your welcome dude ✌🏻

**Pull request merged**
